### ISSUE TITLE
Need GUI

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/PyDictionary#1]
Looking for a good GUI for the application built using flask.

**Comment by ehsabd** [comment]
I can do this in django. Does that work for you? Also I guess you should fork another repo?

**Comment by MarioHdpz** [comment]
I like this one, I think it'll be much more simpler in Flask.

**Comment by aditeyabaral** [comment]
Yep, I think it will be simpler using Flask too, and considering the fact this is a simple application I guess Flask will be enough 👍
