### ISSUE TITLE
Add Spell Check and No Results Found to GUI

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/PyDictionary#11]
The GUI does not support spell check and verbose for no results found. 
These features however exist in the command line variant - 
![image](https://user-images.githubusercontent.com/33230959/95175580-5036d300-07d9-11eb-93fe-c3d5a38a68f9.png)

It would be great if a result card could be added with "No results found" on the results pane (similar to the results obtained for a correct input) with an extremely light red transparent tint for the background colour of the card if possible.

Additionally, another card could be added to display the following

Did you mean?

suggestion 1
suggestion 2
suggestion 3

**Comment by spirulinax** [comment]
Hey, can I work on this?

**Comment by shivamsn97** [comment]
Hello @aditeyabaral, I have completed this task and have opened PR #12  for the same.

**Comment by aditeyabaral** [comment]
Done 👍
