### ISSUE TITLE
Bug Fixes in Flask App

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/PyDictionary#16]
The app seems to have a bug in its logic
![image](https://user-images.githubusercontent.com/33230959/95210819-7ffdcf00-0809-11eb-9988-b579f9c7501c.png)
The original result is retrieved perfectly on command line input
![image](https://user-images.githubusercontent.com/33230959/95210900-9572f900-0809-11eb-83de-8dd76b54ce10.png)

**Comment by MohammedBajuaifer** [comment]
Hi @aditeyabaral, I would like to look into this!

**Comment by aditeyabaral** [comment]
@MohammedBajuaifer 
Sure, go ahead 👍

**Comment by MohammedBajuaifer** [comment]
Would you mind assigning it to me?

**Comment by aditeyabaral** [comment]
@MohammedBajuaifer done 👍

**Comment by shivamsn97** [comment]
I have fixed this issue in #17

**Comment by MohammedBajuaifer** [comment]
.. ok
