### ISSUE TITLE
Minor changes

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/PyDictionary#2]
A few minor changes could be added to source code and the repository such as:

- [ ] Addition of user input for number of examples for sentences
- [ ] Code cleanup and formatting according to pep8 standard
- [ ] Remove option to add to dictionary
- [ ] Convert code into command line based input for faster execution
- [ ] Addition of how to execute code in README
- [ ] Add requirements.txt

Note - PRs with insufficient changes will not be accepted (minimum 3 changes to prevent spam)

**Comment by Sebastien-M** [comment]
Hi! I'd like to work on it, could you assign it to me? :)

**Comment by aditeyabaral** [comment]
Yup, sure go ahead 👍
